services:
  # Main Web Service
  - type: web
    name: taadiway-crm
    env: node
    region: oregon
    plan: starter
    buildCommand: chmod +x scripts/build.sh && ./scripts/build.sh
    startCommand: npm run production:start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: REVALIDATION_SECRET
        generateValue: true
      # Optional: OAuth Providers
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      # Optional: Payment Providers
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      # Optional: Email
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    
databases:
  # PostgreSQL Database (or connect to Neon externally)
  - name: taadiway-db
    plan: starter
    region: oregon
    databaseName: taadiway_crm
    user: taadiway_user
