-- AlterEnum: Add new roles
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'STAFF';

-- AlterTable: Add new User fields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isSuperAdmin" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdById" TEXT;

-- AlterTable: Add new AdminProfile fields
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canManageUsers" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canViewReports" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canManageSettings" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canDeleteData" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canManagePayments" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canExportData" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canManageProducts" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "canApproveRefunds" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "maxDiscountPercent" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "restrictedToClients" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "AdminProfile" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
